image: node:latest
test_server:
  before_script:
    - apt-get update
    - apt-get --yes --force-yes install rsync
  only:
    refs:
      - develop
  script:
      # Search for the ssh-agent  
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
      # Start the ssh-agent
    - eval $(ssh-agent -s)
      # Add the SSH Key stored in the SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
      # Create the .ssh folder
    - mkdir -p ~/.ssh
      # Prevent ssh public key confirmation 
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      
      # Install dependencies
      # Copy (Synchronize) the files to the deployed server
    - ssh root@test.natterbase.com "cd /var/www/html/equilibra_frontend/; git pull; /root/.nvm/versions/node/v12.13.1/bin/npm install; /root/.nvm/versions/node/v12.13.1/bin/npm generate;"

